<?php 
/**
 * @file bg_bebritish.module
 */

/**
 * Implements hook_permission().
 */
function bg_bebritish_permission() {
  return array(
    'administer bg bebritish' => array(
      'title' => 'Administrer BGL BeBritish',
      'description' => 'Effectuer les tâches d\'administration de BGL BeBritish.',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function bg_bebritish_menu() {
  $items = array();
  $items['admin/bgl/bebritish'] = array(
    'title' => 'BeBritish',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bg_bebritish_import_form'),
    'access arguments' => array('administrer bg bebritish'),
    'weight' => -15,
    'file' => 'bg_bebritish.admin.inc',
  );
  $items['admin/bgl/bebritish/import'] = array(
    'title' => 'Import',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/bgl/bebritish/emailing'] = array(
    'title' => 'E-mailing',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bg_bebritish_emailing_form'),
    'access arguments' => array('administrer bg bebritish'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -5,
    'file' => 'bg_bebritish.admin.inc',
  );
  $items['bgl/bebritish/optin/%/%/%'] = array(
    'title' => 'Finaliser votre inscription',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bg_bebritish_password_form', 3, 4, 5),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'bg_bebritish.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_mail().
 * @see bg_bebritish_emailing_form_submit()
 */
function bg_bebritish_mail($key, &$message, $params) {
  switch ($key) {
    case 'optin-bebritish':
      $nom_complet = $params['prenom'] . ' ' . $params['nom'];
      $landing_page = $params['landing_page'];
      $message['subject'] = 'Beaugrenelle - BeBritish';
      $output = "$nom_complet, Beaugrenelle vous salue." . PHP_EOL;
      $output .= PHP_EOL;
      $output .= 'Cliquez sur ce lien pour finaliser votre inscription :' . PHP_EOL;
      $output .= $landing_page . PHP_EOL;
      $output .= PHP_EOL;
      $output .= 'Amicalement,' . PHP_EOL;
      $output .= 'L\'équipe Beaugrenelle.';
      $message['body'][] = $output;
      break;
    default:
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Altération du formulaire d'édition utilisateur.
 */
function bg_bebritish_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  $user = $form_state['user'];
  if (isset($_GET['pass-reset-token']) && isset($_SESSION['pass_reset_' . $user->uid]) && ($_GET['pass-reset-token'] == $_SESSION['pass_reset_' . $user->uid])) {
    // On est dans le cas d'un choix de mot de passe pour compte BeBritish
    // => ajout d'une fonction de soumission custom
    module_load_include('inc', 'bg_bebritish', 'bg_bebritish.pages');
    $form['#submit'][] = 'bg_bebritish_profile_form_submit';
  }
}

/**
 * Redirection vers le front Beaugrenelle après soumission du formulaire d'édition.
 * @see bg_bebritish_form_user_profile_form_alter()
 * @TODO Page de confirmation BeBritish côté front ?
 */
function bg_bebritish_profile_form_submit($form, &$form_state) {
  // Redirection vers Beaugrenelle
  $form_state['redirect'] = 'http://www.beaugrenelle-paris.com/fr/landing-bbritish';
}
